USE dealflow360;

CREATE TABLE customers (
  id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  tier ENUM('BRONZE', 'SILVER', 'GOLD') NOT NULL,
  credit_limit DECIMAL(12,2),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
  id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100) NOT NULL,
  type ENUM('GOOD', 'SERVICE') NOT NULL,
  billing_type ENUM('ONE_TIME', 'RECURRING') NOT NULL,
  sale_price DECIMAL(12,2) NOT NULL,
  cost_price DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'INR',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE warehouses (
  id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
  id VARCHAR(20) PRIMARY KEY,
  warehouse_id VARCHAR(20) NOT NULL,
  product_id VARCHAR(20) NOT NULL,
  available_quantity INT DEFAULT 0,
  reserved_quantity INT DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE users (
  id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('SALES_REP', 'SALES_MANAGER', 'FINANCE_OPERATIONS', 'CUSTOMER', 'ADMIN') NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE discount_rules (
  id VARCHAR(20) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  customer_tier ENUM('BRONZE', 'SILVER', 'GOLD'),
  product_category VARCHAR(100),
  max_discount_percent DECIMAL(5,2) NOT NULL,
  requires_approval_above DECIMAL(5,2) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE upsell_rules (
  id VARCHAR(20) PRIMARY KEY,
  source_category VARCHAR(100) NOT NULL,
  target_name_keywords JSON NOT NULL,
  reason VARCHAR(500) NOT NULL,
  confidence DECIMAL(4,3) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deals (
  id VARCHAR(40) PRIMARY KEY,
  customer_id VARCHAR(20) NOT NULL,
  sales_rep_id VARCHAR(20) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status ENUM('DRAFT','UNDER_REVIEW','APPROVAL_REQUIRED','APPROVED','REJECTED','NEGOTIATION','REAPPROVAL_REQUIRED','FULFILLMENT_PENDING','READY_TO_BILL','CLOSED') NOT NULL DEFAULT 'DRAFT',
  discount_percent DECIMAL(5,2) DEFAULT 0,
  subtotal DECIMAL(12,2) DEFAULT 0,
  discount_amount DECIMAL(12,2) DEFAULT 0,
  total_amount DECIMAL(12,2) DEFAULT 0,
  cost_amount DECIMAL(12,2) DEFAULT 0,
  margin_amount DECIMAL(12,2) DEFAULT 0,
  margin_percent DECIMAL(5,2) DEFAULT 0,
  risk_score INT DEFAULT 0,
  risk_level ENUM('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT 'LOW',
  currency VARCHAR(10) DEFAULT 'INR',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (customer_id) REFERENCES customers(id),
  FOREIGN KEY (sales_rep_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS deal_items (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(40) NOT NULL,
  product_id VARCHAR(20) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  unit_cost DECIMAL(12,2) NOT NULL,
  billing_type ENUM('ONE_TIME','RECURRING') NOT NULL,
  recurring_interval ENUM('MONTHLY','QUARTERLY','YEARLY') NULL,
  discount_percent DECIMAL(5,2) DEFAULT 0,
  subtotal DECIMAL(12,2) NOT NULL,
  total DECIMAL(12,2) NOT NULL,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS deal_warehouses (
  deal_id VARCHAR(20) NOT NULL,
  warehouse_id VARCHAR(20) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (deal_id, warehouse_id),
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS approval_requests (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(40) NOT NULL,
  requested_by VARCHAR(40) NOT NULL,
  approver_role ENUM('SALES_REP','SALES_MANAGER','FINANCE_OPERATIONS','CUSTOMER','ADMIN') NOT NULL,
  status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  reason VARCHAR(500),
  requested_discount_percent DECIMAL(5,2),
  allowed_discount_percent DECIMAL(5,2),
  risk_score INT,
  comments VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (requested_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS deal_events (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(40) NOT NULL,
  event_type ENUM('DEAL_CREATED','DEAL_UPDATED','DISCOUNT_CHANGED','EVALUATION_COMPLETED','APPROVAL_REQUESTED','APPROVED','REJECTED','UPSELL_ADDED','WAREHOUSE_ALLOCATED','NEGOTIATION_STARTED','NEGOTIATION_REQUESTED','REAPPROVAL_TRIGGERED','BILLING_CREATED','STATUS_CHANGED') NOT NULL,
  actor_id VARCHAR(40) NOT NULL,
  description VARCHAR(500) NOT NULL,
  metadata JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS invoices (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(40) NOT NULL,
  customer_id VARCHAR(20) NOT NULL,
  invoice_type ENUM('ONE_TIME','RECURRING') NOT NULL DEFAULT 'ONE_TIME',
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'INR',
  status ENUM('DRAFT','ISSUED','PAID','OVERDUE') NOT NULL DEFAULT 'DRAFT',
  due_date TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(40) NOT NULL,
  product_id VARCHAR(20) NOT NULL,
  billing_interval ENUM('MONTHLY','QUARTERLY','YEARLY') NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  next_billing_date TIMESTAMP NULL,
  status ENUM('ACTIVE','PAUSED','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS warehouse_allocations (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(20) NOT NULL,
  warehouse_id VARCHAR(20) NOT NULL,
  warehouse_name VARCHAR(255) NOT NULL,
  product_id VARCHAR(20) NOT NULL,
  quantity INT NOT NULL,
  status ENUM('ALLOCATED','PARTIAL','UNAVAILABLE') NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS negotiations (
  id VARCHAR(40) PRIMARY KEY,
  deal_id VARCHAR(40) NOT NULL,
  actor_id VARCHAR(40) NOT NULL,
  description TEXT NOT NULL,
  proposed_discount_percent DECIMAL(5,2) DEFAULT NULL,
  note VARCHAR(500) DEFAULT NULL,
  status ENUM('OPEN','CLOSED','REJECTED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE,
  FOREIGN KEY (actor_id) REFERENCES users(id)
);